const { chromium }=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8080');await page.screenshot({path:'/workspace/scratch/8a96ebc02f6d/quiz-desktop.png',fullPage:true});
 await page.locator('#start').click();await page.locator('#next').click();assert.match(await page.locator('#quiz-error').textContent(),/Selecciona/);
 const cases=[
 {key:'oferta',a:{service:'coach',stage:'idea',clarity:'mixed',execution:'zero',leads:'zero',channel:'none',validation:'none',barrier:'offer',perceived:'oferta',goal:'validate'}},
 {key:'ejecucion',a:{service:'consult',stage:'offer',clarity:'clear',execution:'zero',leads:'zero',channel:'content',validation:'buyers',barrier:'exposure',perceived:'ejecucion',goal:'launch'}},
 {key:'captacion',a:{service:'professional',stage:'sales',clarity:'clear',execution:'many',leads:'zero',channel:'content',validation:'buyers',barrier:'channel',perceived:'captacion',goal:'leads'}},
 {key:'conversion',a:{service:'therapy',stage:'sales',clarity:'clear',execution:'few',leads:'some',channel:'referrals',process:'stuck',capacity:'reactive',perceived:'conversion',goal:'sales'}},
 {key:'organizacion',a:{service:'coach',stage:'steady',clarity:'clear',execution:'many',leads:'many',channel:'content',process:'followup',capacity:'reactive',perceived:'organizacion',goal:'order'}}
 ];
 async function complete(p,c){await p.goto('http://127.0.0.1:8080');await p.locator('#start').click();if(await p.locator('#contact-form').count()){await p.locator('[name=name]').fill('Prueba');await p.locator('[name=email]').fill('prueba@example.com');await p.locator('[name=phone]').fill('+573001234567');await p.locator('[name=consent]').check();await p.locator('#contact-form button').click();await p.waitForSelector('#contact-form',{state:'detached'});}for(let i=0;i<5;i++){const names=await p.locator('#questions fieldset').evaluateAll(es=>es.map(e=>e.dataset.question));for(const name of names)await p.locator(`input[name="${name}"][value="${({revenue:"under1k",pricing:"undefined",...c.a})[name]}"]`).check();await p.locator('#next').click()}assert.equal(await p.evaluate(()=>state.result.key),c.key);assert(await p.locator('#result').isVisible())}
 for(const c of cases)await complete(page,c);
 assert.equal(await page.evaluate(()=>diagnose({stage:'sales',clarity:'clear',execution:'unknown',leads:'unknown'}).provisional),true);
 await page.locator('#edit-answers').click();await page.locator('#next').click();await page.locator('#next').click();await page.locator('input[name=leads][value=zero]').check();await page.locator('#next').click();assert(await page.locator('[name=validation]').first().isVisible());assert.equal(await page.locator('[name=process]').count(),0);
 await complete(page,cases[3]);await page.screenshot({path:'/workspace/scratch/8a96ebc02f6d/quiz-result.png',fullPage:true});
 const dl=page.waitForEvent('download');await page.locator('#download').click();const file=await dl;assert.equal(file.suggestedFilename(),'Mi-plan-Jumpers.txt');
 await page.locator('#prepare').click();await page.locator('#support').selectOption({label:'Mentoría para trabajar mi estrategia'});await page.locator('#timing').selectOption({label:'Durante las próximas dos semanas'});await page.locator('#context').fill('<img src=x onerror=alert(1)>');await page.locator('#help-form button[type=submit]').click();assert(await page.locator('#summary-area').isVisible());assert.equal(await page.locator('#summary-area img').count(),0);assert.match(await page.locator('#summary-text').textContent(),/Conversión/);
 await page.locator('#privacy-link').click();assert(await page.locator('#privacy').isVisible());await page.locator('#privacy-back').click();assert(await page.locator('#result').isVisible());
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1});await mobile.goto('http://127.0.0.1:8080');assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:'/workspace/scratch/8a96ebc02f6d/quiz-mobile.png',fullPage:true});await complete(mobile,cases[1]);assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.locator('#edit-answers').click();await mobile.screenshot({path:'/workspace/scratch/8a96ebc02f6d/quiz-questions.png',fullPage:true});
 const connected=await browser.newPage();const html=fs.readFileSync(__dirname+'/../index.html','utf8').replace("leadEndpoint: ''","leadEndpoint: 'https://example.com/intake'");await connected.route('http://127.0.0.1:8080/',r=>r.fulfill({contentType:'text/html',body:html}));let received;
 await connected.route('https://example.com/intake',r=>{received=JSON.parse(r.request().postData());return r.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify({ok:true,id:received.id})})});
 await complete(connected,cases[2]);
 for(const [intent,timing,commitment,investment,expected] of [['learn','now','yes','ready','youtube'],['personal','now','yes','ready','mentoria'],['community','now','yes','community','skool'],['personal','explore','yes','ready','youtube']]){
 for(const [key,value] of Object.entries({intent,timing,commitment,investment}))await connected.locator('#route-form [name='+key+']').selectOption(value);
 await connected.locator('#route-form button').click();await connected.waitForFunction(()=>document.querySelector('#route-status').textContent.includes('quedó guardado'));
 assert.equal(await connected.evaluate(()=>state.route),expected);assert.equal(received.event,'qualified');
 }
 const failed=await browser.newPage();await failed.route('http://127.0.0.1:8080/',r=>r.fulfill({contentType:'text/html',body:html}));await failed.route('https://example.com/intake',r=>r.fulfill({contentType:'application/json',body:'{"ok":false}'}));await failed.goto('http://127.0.0.1:8080');await failed.locator('#start').click();for(const [key,value] of Object.entries({name:'Prueba',email:'test@example.com',phone:'+573001234567'}))await failed.locator('[name='+key+']').fill(value);await failed.locator('[name=consent]').check();await failed.locator('#contact-form button').click();await failed.waitForFunction(()=>document.querySelector('#contact-status').textContent.includes('No pudimos'));assert(await failed.locator('#contact-form button').isEnabled());assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: 5 result routes; insufficient data; missing answers; conditional back-navigation; download; escaped summary; privacy; mobile overflow; mocked capture success + failure; zero JS errors.');
})().catch(e=>{console.error(e);process.exit(1)});
